# Auto-generated from MRtrix C++ command with '__print_pydra_code__' secret option

from typing import Any
from pathlib import Path  # noqa: F401
from fileformats.generic import File, Directory  # noqa: F401
from fileformats.vendor.mrtrix3.medimage import ImageIn, ImageOut, Tracks  # noqa: F401
from pydra.compose import shell
from pydra.utils.typing import MultiInputObj


@shell.define
class FixelFilter(shell.Task["FixelFilter.Outputs"]):
    """If the first input to the command is a specific fixel data file, then a filtered version of only that file will be generated by the command. Alternatively, if the input is the location of a fixel directory, then the command will create a duplicate of the fixel directory, and apply the specified filter operation to all fixel data files within the directory.

        Fixel data are stored utilising the fixel directory format described in the main documentation, which can be found at the following link:
    https://mrtrix.readthedocs.io/en/3.0.7/fixel_based_analysis/fixel_directory_format.html


        References
        ----------

            Tournier, J.-D.; Smith, R. E.; Raffelt, D.; Tabbara, R.; Dhollander, T.; Pietsch, M.; Christiaens, D.; Jeurissen, B.; Yeh, C.-H. & Connelly, A. MRtrix3: A fast, flexible and open software framework for medical image processing and visualisation. NeuroImage, 2019, 202, 116137


        MRtrix
        ------

        Version:3.0.7-1583-g24a09ac5-dirty, built Dec  3 2025

        Author: Robert E. Smith (robert.smith@florey.edu.au)

        Copyright: Copyright (c) 2008-2025 the MRtrix3 contributors.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Covered Software is provided under this License on an "as is"
    basis, without warranty of any kind, either expressed, implied, or
    statutory, including, without limitation, warranties that the
    Covered Software is free of defects, merchantable, fit for a
    particular purpose or non-infringing.
    See the Mozilla Public License v. 2.0 for more details.

    For more details, see http://www.mrtrix.org/.
    """

    executable = "fixelfilter"

    # Arguments
    in_file: Directory | ImageIn = shell.arg(
        argstr="",
        position=1,
        help="""the input: either a fixel data file, or a fixel directory (see Description)""",
    )
    filter: str = shell.arg(
        argstr="",
        position=2,
        help="""the filtering operation to perform; options are: cfe, connect, smooth""",
        allowed_values=["cfe", "connect", "smooth"],
    )

    # Options
    matrix: Directory = shell.arg(
        argstr="-matrix",
        help="""provide a fixel-fixel connectivity matrix for filtering operations that require it""",
    )
    mask: ImageIn | None = shell.arg(
        default=None,
        argstr="-mask",
        help="""constrain the filter to operate within a specified binary fixel mask""",
    )

    # Parameters for the Connectivity-based Fixel Enhancement (CFE) algorithm:
    cfe_dh: float | None = shell.arg(
        default=None,
        argstr="-cfe_dh",
        help="""the height increment used in the cfe integration (default: 0.1)""",
    )
    cfe_e: float | None = shell.arg(
        default=None,
        argstr="-cfe_e",
        help="""cfe extent exponent (default: 2)""",
    )
    cfe_h: float | None = shell.arg(
        default=None,
        argstr="-cfe_h",
        help="""cfe height exponent (default: 3)""",
    )
    cfe_c: float | None = shell.arg(
        default=None,
        argstr="-cfe_c",
        help="""cfe connectivity exponent (default: 0.5)""",
    )
    cfe_legacy: bool = shell.arg(
        default=False,
        argstr="-cfe_legacy",
        help="""use the legacy (non-normalised) form of the cfe equation""",
    )

    # Options specific to the "connect" filter:
    threshold_value: float | None = shell.arg(
        default=None,
        argstr="-threshold_value",
        help="""specify a threshold for the input fixel data file values (default = 0.5)""",
    )
    threshold_connectivity: float | None = shell.arg(
        default=None,
        argstr="-threshold_connectivity",
        help="""specify a fixel-fixel connectivity threshold for connected-component analysis (default = 0.1)""",
    )

    # Options specific to the "smooth" filter:
    fwhm: float | None = shell.arg(
        default=None,
        argstr="-fwhm",
        help="""the full-width half-maximum (FWHM) of the spatial component of the smoothing filter (default = 10mm)""",
    )
    minweight: float | None = shell.arg(
        default=None,
        argstr="-minweight",
        help="""apply a minimum threshold to smoothing weights (default = 0.01)""",
    )

    # Standard options
    info: bool = shell.arg(
        default=False,
        argstr="-info",
        help="""display information messages.""",
    )
    quiet: bool = shell.arg(
        default=False,
        argstr="-quiet",
        help="""do not display information messages or progress status; alternatively, this can be achieved by setting the MRTRIX_QUIET environment variable to a non-empty string.""",
    )
    debug: bool = shell.arg(
        default=False,
        argstr="-debug",
        help="""display debugging messages.""",
    )
    force: bool = shell.arg(
        default=False,
        argstr="-force",
        help="""force overwrite of output files (caution: using the same file as input and output might cause unexpected behaviour).""",
    )
    nthreads: int | None = shell.arg(
        default=None,
        argstr="-nthreads",
        help="""use this number of threads in multi-threaded applications (set to 0 to disable multi-threading).""",
    )
    config: MultiInputObj[tuple[str, str]] | None = shell.arg(
        default=None,
        argstr="-config",
        help="""temporarily set the value of an MRtrix config file entry.""",
        sep=" ",
    )

    class Outputs(shell.Outputs):
        out_file: Directory | ImageOut = shell.outarg(
            argstr="",
            position=3,
            path_template="out_file.mif",
            help="""the output: either a fixel data file, or a fixel directory (see Description)""",
        )
