# Auto-generated by mrtrix3/app.py:print_pydra_code()

from typing import Any
from pathlib import Path  # noqa: F401
from fileformats.generic import FsObject, File, Directory  # noqa: F401
from fileformats.vendor.mrtrix3.medimage import Tracks, ImageIn, ImageOut  # noqa: F401
from pydra.utils.typing import MultiInputObj
from pydra.compose import shell


@shell.define(
    xor=[["info", "quiet", "debug", None], ["noshuffle", "notransform", None]]
)
class PeaksCheck(shell.Task["PeaksCheck.Outputs"]):
    """

    References
    ----------

    Tournier, J.-D.; Smith, R. E.; Raffelt, D.; Tabbara, R.; Dhollander, T.; Pietsch, M.; Christiaens, D.; Jeurissen, B.; Yeh, C.-H. & Connelly, A. MRtrix3: A fast, flexible and open software framework for medical image processing and visualisation. NeuroImage, 2019, 202, 116137

    --------------



    **Author:** Robert E. Smith (robert.smith@florey.edu.au)

    **Copyright:** Copyright (c) 2008-2025 the MRtrix3 contributors.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Covered Software is provided under this License on an "as is"
    basis, without warranty of any kind, either expressed, implied, or
    statutory, including, without limitation, warranties that the
    Covered Software is free of defects, merchantable, fit for a
    particular purpose or non-infringing.
    See the Mozilla Public License v. 2.0 for more details.

    For more details, see http://www.mrtrix.org/.

    """

    executable = "peakscheck"

    in_file: ImageIn = shell.arg(
        position=1,
        argstr="",
        help="The input fibre orientations image to be checked",
    )
    nocleanup: bool = shell.arg(
        help="do not delete intermediate files during script execution, and do not delete scratch directory at script completion.",
        argstr="-nocleanup",
        default=False,
    )
    scratch: Directory | None = shell.arg(
        help="manually specify an existing directory in which to generate the scratch directory.",
        argstr="-scratch",
        default=None,
    )
    cont: str | None = shell.arg(
        help="continue the script from a previous execution; must provide the scratch directory path, and the name of the last successfully-generated file.",
        argstr="-cont",
        default=None,
    )
    info: bool = shell.arg(
        help="display information messages.",
        argstr="-info",
        default=False,
    )
    quiet: bool = shell.arg(
        help="do not display information messages or progress status. Alternatively, this can be achieved by setting the MRTRIX_QUIET environment variable to a non-empty string.",
        argstr="-quiet",
        default=False,
    )
    debug: bool = shell.arg(
        help="display debugging messages.",
        argstr="-debug",
        default=False,
    )
    force: bool = shell.arg(
        help="force overwrite of output files.",
        argstr="-force",
        default=False,
    )
    nthreads: int | None = shell.arg(
        help="use this number of threads in multi-threaded applications (set to 0 to disable multi-threading).",
        argstr="-nthreads",
        default=None,
    )
    config: MultiInputObj[MultiInputObj] = shell.arg(
        help="temporarily set the value of an MRtrix config file entry.",
        argstr="-config",
        default=None,
    )
    help: bool = shell.arg(
        help="display this information page and exit.",
        argstr="-help",
        default=False,
    )
    version: bool = shell.arg(
        help="display version information and exit.",
        argstr="-version",
        default=False,
    )
    mask: ImageIn | None = shell.arg(
        help="Provide a mask image within which to seed & constrain tracking",
        argstr="-mask",
        default=None,
    )
    number: int | None = shell.arg(
        help="Set the number of tracks to generate for each test",
        argstr="-number",
        default=None,
    )
    threshold: float | None = shell.arg(
        help="Modulate thresold on the ratio of empirical to maximal mean length to issue an error",
        argstr="-threshold",
        default=None,
    )
    format: str | None = shell.arg(
        help="The format in which peak orientations are specified; one of: spherical,unitspherical,3vector,unit3vector",
        allowed_values=["spherical", "unitspherical", "3vector", "unit3vector"],
        argstr="-format",
        default=None,
    )
    reference: str | None = shell.arg(
        help="The a priori expected references axes against which the input orientations are defined; one of: xyz,ijk,fsl",
        allowed_values=["xyz", "ijk", "fsl"],
        argstr="-reference",
        default=None,
    )
    noshuffle: bool = shell.arg(
        help="Do not evaluate possibility of requiring shuffles of axes or angles; only consider prospective transforms from alternative reference frames to real / scanner space",
        argstr="-noshuffle",
        default=False,
    )
    notransform: bool = shell.arg(
        help="Do not evaluate possibility of requiring transform of peak orientations from image to real / scanner space; only consider prospective shuffles of axes or angles",
        argstr="-notransform",
        default=False,
    )
    all: bool = shell.arg(
        help="Print table containing all results to standard output",
        argstr="-all",
        default=False,
    )

    class Outputs(shell.Outputs):
        out_table: File | None = shell.outarg(
            help="Write text file with table containing all results",
            argstr="-out_table",
            default=None,
            path_template="out_table.txt",
        )
