[pytest]
# fileformats.vendor.mrtrix3 is a namespace package, which pytest needs to be told
# about to import the test modules within it by their full names
consider_namespace_packages = true
#log_cli=true
#log_level=NOTSET
filterwarnings =
    default::DeprecationWarning:__main__
    ignore::DeprecationWarning
    ignore::_pytest.warning_types.PytestCollectionWarning
    ignore::PendingDeprecationWarning
